version: "3.9"
services:
    db:
        image: postgres:13.3
        environment:
            POSTGRES_DB: "laravel"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
        volumes:
            - /custom/mount:/var/lib/postgresql/data
        ports:
            - "5432:5432"
